/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountInfo: typeof import('./../src/views/dashboard/components/countInfo.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect'];
    FollowChart: typeof import('./../src/views/dashboard/components/followChart.vue')['default'];
    IconSelect: typeof import('./../src/components/iconSelect.vue')['default'];
    'IEp:expand': typeof import('~icons/ep/expand')['default'];
    'IEp:fold': typeof import('~icons/ep/fold')['default'];
    'IEp:switchButton': typeof import('~icons/ep/switch-button')['default'];
    InterviewChart: typeof import('./../src/views/dashboard/components/interviewChart.vue')['default'];
    ISyLang: typeof import('~icons/sy/lang')['default'];
    ISyVue: typeof import('~icons/sy/vue')['default'];
    RichEditor: typeof import('./../src/components/richEditor.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SelectLang: typeof import('./../src/components/selectLang.vue')['default'];
    SvgIcon: typeof import('./../src/components/svgIcon.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
